server:
  port: 10001

logging:
    level:
        com:
            wensheng: TRACE
        root: WARN
mongodb:
  original:
    host: 10.20.100.227
    port: 27017
    database: wensheng
  wszcc:
    host: 10.20.100.227
    port: 27017
    database: wszcc

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
      password: wensheng
      url: jdbc:mysql://10.20.100.70:3306/ZCC_AMC?useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20



mybatis:
  type-aliases-package: com.wensheng.zcc.amc.module
  mapper-locations:
    - classpath:mappers/*Mapper.xml
    - classpath:mappers/extends/*Mapper.xml

project:
  params:
    debt_image_path: /disk/temp/debt/images/
    asset_image_path: /disk/temp/asset/images/
    oss_end_point: oss-cn-beijing.aliyuncs.com
    oss_key_id: LTAIr4FuhRp7SciF
    oss_key_secret: jTtg1M1J39fTJewIwNDNnz09rGeBzC
    bucket_name: ws-zcc

