server:
  port: 10001

logging:
    level:
        com:
            wensheng: TRACE
        root: WARN
mongodb:
  original:
    host: 10.20.100.227
    port: 27017
    database: wensheng
  wszcc:
    host: 10.20.100.227
    port: 27017
    database: wszcc

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
      password: wensheng
      url: jdbc:mysql://10.20.100.70:3306/ZCC_AMC?useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  security:
    oauth2:
      client:
        registration:
          sample:
            client-id: sampleClientId
            authorizedGrantTypes: implicit
            scops: read,write
            accessTokenValiditySeconds: 3600
          amc-client-thirdpart:
            client-id: amcClient3rdPartId
            secret: secret
            scopes: thirdpart, read
            authorizedGrantTypes: implicit, refresh_token, client_credentials
          amc-admin:
            client-id: amcAdminId
            secret: secret
            scopes: amcAdmin,amcClient,read,write
            authorizedGrantTypes: password, authorization_code, refresh_token, client_credentials
            redirectUris: admin,http://localhost:10003/amc/login, http://localhost:8080/login/oauth2/code/custom, http://localhost:8080/ui-thymeleaf/login/oauth2/code/custom, http://localhost:8080/authorize/oauth2/code/bael, http://localhost:8080/login/oauth2/code/bael
          amc-client:
            client-id: amcClientId
            secret: secret
            scopes: amcClient,read,write
            redirectUris: client,http://localhost:10003/amc/login
            authorizedGrantTypes: password, authorization_code, refresh_token, client_credentials
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

mybatis:
  type-aliases-package: com.wensheng.zcc.amc.module
  mapper-locations:
    - classpath:mappers/*Mapper.xml
    - classpath:mappers/extends/*Mapper.xml

project:
  params:
    debt_image_path: /disk/temp/debt/images/
    asset_image_path: /disk/temp/asset/images/
    qrcode_image_path: /disk/temp/qrcode/images/
    oss_end_point: oss-cn-beijing.aliyuncs.com
    oss_key_id: LTAIr4FuhRp7SciF
    oss_key_secret: jTtg1M1J39fTJewIwNDNnz09rGeBzC
    bucket_name: ws-zcc

---
# tag::wechatConfig
wechat:
  miniapp:
    appId: wxdb885be2c95a5b32
    appSecret: 279bfb3dd9d3e5eb43c480f625afdc0b
    get_token_url: https://api.weixin.qq.com/cgi-bin/token
    get_qrcode_url: https://api.weixin.qq.com/wxa/getwxacodeunlimit

# end::wechatConfig