server:
  port: 10001

logging:
    level:
        com:
            wensheng: TRACE
        root: WARN
mongodb:
  primary:
    host: 10.20.100.227
    port: 27017
    database: wensheng
  secondary:
    host: 10.20.100.236
    port: 27017
    database: second

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
      password: wensheng
      url: jdbc:mysql://10.20.100.70:3306/ZCC_AMC?useUnicode=true&characterEncoding=utf-8
      username: root
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


#  jpa:
#      generate-ddl: false
#      hibernate:
#          ddl-auto: 'none'
#          naming:
#              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      properties:
#          hibernate:
#              hbm2ddl:
#                  auto: none
#      show-sql: true
  user:
      datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.wensheng.zcc.amc.module
  mapper-locations: classpath:mappers/*Mapper.xml

project:
  params:
    debt_image_path: /disk/temp/debt/images/
    asset_image_path: /disk/temp/asset/images/
    oss-end-point: oss-cn-beijing.aliyuncs.com
    oss-key-id: LTAIr4FuhRp7SciF
    oss-key-secret: jTtg1M1J39fTJewIwNDNnz09rGeBzC
    bucket-name: ws-zcc

