
spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    datasource:
        password: wensheng
        url: jdbc:mysql://10.20.100.70:3306/ZCC_SSO?useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
        username: root
        driverClassName: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    jpa:
#        generate-ddl: false
#        hibernate:
#            ddl-auto: 'none '
#            naming:
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        properties:
#            hibernate:
#                hbm2ddl:
#                    auto: none
#        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    sample:
                        client-id: sampleClientId
                        authorizedGrantTypes: implicit
                        scops: read,write
                        accessTokenValiditySeconds: 3600
                    amc-client:
                        client-id: amcClientId
                        secret: secret
                        authorizedGrantTypes: password, authorization_code, refresh_token, client_credentials

mybatis:
    type-aliases-package: com.wensheng.zcc.sso.module
    mapper-locations:
        - classpath:mappers/*Mapper.xml
        - classpath:mappers/ext/*Mapper.xml

weixin:
    appId: wxdb885be2c95a5b32
    appSecret: 279bfb3dd9d3e5eb43c480f625afdc0b
    get_token_url: https://api.weixin.qq.com/cgi-bin/token
    get_qrcode_url: https://api.weixin.qq.com/wxa/getwxacodeunlimit




auth-server:
    - client:
        - clientId: sampleClientId
        -

logging:
    level:
        com:
            wensheng: TRACE
        root: WARN