server:
  port: 10003
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    consumer:
      group-id: grp-zcc-logger
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: ${env.kafka-host}:9092

  data:
    mongodb:
#      authentication-database= # Authentication database name.
      database: wszcc-log # Database name.
#      field-naming-strategy= # Fully qualified name of the FieldNamingStrategy to use.
#      grid-fs-database= # GridFS database name.
      host: 10.20.100.236 # Mongo server host.
#      password= # Login password of the mongo server.
      port: 27017 # Mongo server port.
      repositories:
        type: auto
#      uri=mongodb://localhost/test # Mongo database URI. When set, host and port are ignored.
#      username= # Login user of the mongo server.

kafka:
  topic-wechat-userlocation: topic_wechat_userLocation_${env.env-prefix}

env:
  env-prefix: dev
  kafka-host: 10.20.100.238