server:
  port: 10003
spring:
  autoconfigure:
    exclude:
#      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  kafka:
    consumer:
      group-id: grp-zcc-logger
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: ${env.kafka-host}:9092
#  jpa:
#      generate-ddl: false
#      hibernate:
#          ddl-auto: 'none'
#          naming:
#              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      properties:
#          hibernate:
#              hbm2ddl:
#                  auto: none
#      show-sql: true
  data:
    mongodb:
      database: wszcc_log
      host: 10.20.100.235
      port: 27017

mongodb:
  wszcc_sso:
    host: 10.20.100.235
    port: 27017
    database: wszcc_log

kafka:
  topic-wechat-userlocation: topic_wechat_userLocation_${env.env-prefix}
  topic_amc_useroper: topic_amc_userOper_${env.env-prefix}

env:
  env-prefix: dev
  kafka-host: 10.20.100.238